invader-refactor -M move -r "mek" "cmt"
invader-refactor -M move -r "cmt" "cmt\spv1"


echo "Processing Powerup Tags"
invader-refactor -M move -r "cmt\spv1\powerups\cloaking device activated" "cmt\spv1\powerups\overshield"
invader-refactor -M move -r "cmt\spv1\powerups\health restored" "cmt\spv1\powerups\medkit"
invader-refactor -M move -r "cmt\spv1\powerups\m6d pistol ammo" "cmt\spv1\powerups\pistol ammo"
invader-refactor -M move -r "cmt\spv1\powerups\m9 he dp grenade" "cmt\spv1\weapons\human\frag grenade"
invader-refactor -M move -r "cmt\spv1\powerups\ma5b assault rifle ammo" "cmt\spv1\powerups\ar ammo"
invader-refactor -M move -r "cmt\spv1\powerups\plasma grenade" "cmt\spv1\weapons\covenant\plasma grenade"
invader-refactor -M move -r "cmt\spv1\powerups\primary br55 m45 battle rifle ammo" "cmt\spv1\powerups\br ammo"


echo "Processing Weapon Tags"
invader-refactor -M move -r "cmt\spv1\weapons\br55 m45 battle rifle" "cmt\spv1\weapons\human\br_grenade"
invader-refactor -M move -r "cmt\spv1\weapons\galileian" "cmt\spv1\weapons\human\spartan laser"
invader-refactor -M move -r "cmt\spv1\weapons\m6d pistol" "cmt\spv1\weapons\human\pistol"
invader-refactor -M move -r "cmt\spv1\weapons\m5 caseless smg" "cmt\spv1\weapons\human\smg"
invader-refactor -M move -r "cmt\spv1\weapons\m19 ssm rocket launcher" "cmt\spv1\weapons\human\rocket_launcher"
invader-refactor -M move -r "cmt\spv1\weapons\m90 shotgun" "cmt\spv1\weapons\human\shotgun"
invader-refactor -M move -r "cmt\spv1\weapons\m7057 flamethrower" "cmt\spv1\weapons\human\flamethrower"
invader-refactor -M move -r "cmt\spv1\weapons\ma5b assault rifle" "cmt\spv1\weapons\human\assault_rifle"
invader-refactor -M move -r "cmt\spv1\weapons\s108 am sniper rifle" "cmt\spv1\weapons\human\stealth_sniper"


invader-refactor -M move -r "cmt\spv1\weapons\needler" "cmt\spv1\weapons\covenant\needler"
invader-refactor -M move -r "cmt\spv1\weapons\plasma pistol" "cmt\spv1\weapons\covenant\plasma_pistol"
invader-refactor -M move -r "cmt\spv1\weapons\plasma rifle" "cmt\spv1\weapons\covenant\plasma_rifle"
invader-refactor -M move -r "cmt\spv1\weapons\m6c magnum" "cmt\spv1\weapons\covenant\hunter_gun"
invader-refactor -M move -r "cmt\spv1\weapons\plasma grenade" "cmt\spv1\weapons\covenant\plasma grenade"

echo "Adjusting Weapon tag names"
invader-refactor -M move -T "cmt\spv1\weapons\covenant\needler\needler.weapon" "cmt\spv1\weapons\covenant\needler\needler.weapon"
invader-refactor -M move -T "cmt\spv1\weapons\covenant\plasma_rifle\plasma rifle.weapon" "cmt\spv1\weapons\covenant\plasma_rifle\plasma rifle sp.weapon"
invader-refactor -M move -T "cmt\spv1\weapons\human\assault_rifle\ma5b assault rifle.weapon" "cmt\spv1\weapons\human\assault_rifle\assault rifle.weapon"
invader-refactor -M move -T "cmt\spv1\weapons\human\br_grenade\br55 m45 battle rifle.weapon" "cmt\spv1\weapons\human\br_grenade\br_grenade sp.weapon"
invader-refactor -M move -T "cmt\spv1\weapons\human\flamethrower\m7057 flamethrower.weapon" "cmt\spv1\weapons\human\flamethrower\flamethrower.weapon"
invader-refactor -M move -T "cmt\spv1\weapons\human\pistol\m6d pistol.weapon" "cmt\spv1\weapons\human\pistol\pistol.weapon"
invader-refactor -M move -T "cmt\spv1\weapons\human\rocket_launcher\m19 ssm rocket launcher.weapon" "cmt\spv1\weapons\human\rocket_launcher\rocket launcher sp.weapon"
invader-refactor -M move -T "cmt\spv1\weapons\human\shotgun\m90 shotgun.weapon" "cmt\spv1\weapons\human\shotgun\shotgun.weapon"
invader-refactor -M move -T "cmt\spv1\weapons\human\smg\m5 caseless smg.weapon" "cmt\spv1\weapons\human\smg\smg.weapon"
invader-refactor -M move -T "cmt\spv1\weapons\human\spartan laser\galileian.weapon" "cmt\spv1\weapons\human\spartan laser\spartanlaser sp.weapon"
invader-refactor -M move -T "cmt\spv1\weapons\human\stealth_sniper\s108 am sniper rifle.weapon" "cmt\spv1\weapons\human\stealth_sniper\sniper rifle.weapon"
invader-refactor -M move -T "cmt\spv1\weapons\covenant\hunter_gun\m6c magnum.weapon" "cmt\spv1\weapons\covenant\hunter_gun\hunter_gun.weapon"


echo "Processing Vehicle Tags"
invader-refactor -M move -r "cmt\spv1\vehicles\m12 warthog lrv" "cmt\spv1\vehicles\warthog_chain"
invader-refactor -M move -r "cmt\spv1\vehicles\m12a2 warthog laav" "cmt\spv1\vehicles\warthog_rocket"
invader-refactor -M move -r "cmt\spv1\vehicles\m808b scorpion mbt" "cmt\spv1\vehicles\scorpion"
invader-refactor -M move -r "cmt\spv1\vehicles\d77 tc pelican dropship" "cmt\spv1\vehicles\pelican"
invader-refactor -M move -r "cmt\spv1\vehicles\protected 1578" "cmt\spv1\vehicles\cryopod"
invader-refactor -M move -T "cmt\spv1\vehicles\cryopod\protected 1578.vehicle" "cmt\spv1\vehicles\cryopod\cyropod.vehicle"
invader-refactor -M move -r "cmt\spv1\vehicles\protected 1854" "cmt\spv1\vehicles\lifepod_reentry"
invader-refactor -M move -T "cmt\spv1\vehicles\lifepod_reentry\protected 1854.vehicle" "cmt\spv1\vehicles\lifepod_reentry\lifepod_reentry.vehicle"

invader-refactor -M move -T "cmt\spv1\vehicles\scorpion\m808b scorpion mbt.vehicle" "cmt\spv1\vehicles\scorpion\scorpion sp.vehicle" 

echo "Processing biped Tags"
invader-refactor -M move -r "cmt\spv1\characters\player_sp" "cmt\spv1\characters\spartan_sp"
invader-refactor -M move -r "cmt\spv1\characters\mc" "cmt\spv1\characters\spartan_sp"
invader-refactor -M no-move -T "cmt\spv1\characters\spartan_sp\mc.biped" "cmt\spv1\characters\spartan_sp\player_sp.biped"
invader-refactor -M no-move -T "cmt\spv1\characters\spartan_sp\mc #1.biped" "cmt\spv1\characters\spartan_sp\player_sp.biped"
invader-refactor -M move -r "cmt\spv1\characters\protected 304" "cmt\spv1\characters\crewman"
invader-refactor -M move -T "cmt\spv1\characters\crewman\protected 2819.biped" "cmt\spv1\characters\crewman\crewman.biped"
invader-refactor -M no-move -T "cmt\spv1\characters\protected 1570\protected 1570.biped" "characters\pilot\pilot.biped"
invader-refactor -M move -r "cmt\spv1\characters\protected 2352" "cmt\spv1\characters\elite"
invader-refactor -M move -T "cmt\spv1\characters\elite\protected 2820.biped" "cmt\spv1\characters\elite\elite.biped"
invader-refactor -M move -r "cmt\spv1\characters\protected 2585" "cmt\spv1\characters\grunt"
invader-refactor -M move -T "cmt\spv1\characters\grunt\protected 2814.biped" "cmt\spv1\characters\grunt\grunt.biped"
invader-refactor -M no-move -T "cmt\spv1\characters\protected 2823\protected 2821.biped" "characters\marine\marine.biped"
invader-refactor -M move -r "cmt\spv1\characters\protected 2840" "cmt\spv1\characters\hunter"
invader-refactor -M move -T "cmt\spv1\characters\hunter\protected 2838.biped" "cmt\spv1\characters\hunter\hunter.biped"


echo "Processing Scenery Tags"
invader-refactor -M no-move -T "cmt\spv1\scenery\protected 31\protected 31.scenery" "scenery\tubewire\tubewire.scenery" 
invader-refactor -M no-move -T "cmt\spv1\scenery\protected 37\protected 37.scenery" "scenery\h_barricade_large\h_barricade_large.scenery" 
invader-refactor -M no-move -T "cmt\spv1\scenery\protected 51\protected 51.scenery" "scenery\h_barricade_large_gap\h_barricade_large_gap.scenery" 
invader-refactor -M no-move -T "cmt\spv1\scenery\protected 54\protected 54.scenery" "scenery\h_barricade_small_visor\h_barricade_small_visor.scenery" 
invader-refactor -M move -r "cmt\spv1\scenery\protected 57" "cmt\spv1\scenery\fire_smokeless" 
invader-refactor -M no-move -T "cmt\spv1\scenery\protected 119\protected 119.scenery" "levels\a10\devices\h computer bank\h computer bank.scenery" 
invader-refactor -M move -r "cmt\spv1\scenery\protected 146" "cmt\spv1\scenery\fire_smokey" 
invader-refactor -M no-move -T "cmt\spv1\scenery\protected 223\protected 223.scenery" "levels\a10\devices\hushed casket-on\hushed casket-on.scenery" 
invader-refactor -M no-move -T "cmt\spv1\scenery\protected 227\protected 227.scenery" "levels\a10\devices\hushed casket-off\hushed casket-off.scenery"
invader-refactor -M move -r "cmt\spv1\scenery\protected 257" "cmt\spv1\scenery\red_light" 
invader-refactor -M no-move -T "cmt\spv1\scenery\protected 267\protected 267.scenery" "vehicles\lifepod\lifepod.scenery"

echo "Processing Misc Tags"
invader-refactor -M move -r "cmt\spv1\scenery\m6d pistol" "cmt\spv1\weapons\human\pistol"
pause